import { ShieldAlert } from "lucide-react";

export function ResponsibleAi() {
  return (
    <div className="flex items-start gap-3 rounded-xl border bg-pastel-peach/40 px-4 py-3 text-sm text-foreground/80">
      <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
      <p>
        <span className="font-semibold text-foreground">Responsible AI:</span>{" "}
        Outputs are generated by an AI model and may contain errors, bias, or
        outdated information. Review and edit before sharing or making
        decisions. Do not submit confidential data you are not comfortable
        sending to a cloud model.
      </p>
    </div>
  );
}
